src/modes/top10/Top10.svelte
src/modes/top10/Top10Sensor.svelte

fix: top10 error occurred

---

src/modes/exportdata/ExportData.svelte

feat: add ack hint

---

src/stores/constants.js

sync with https://docs.google.com/document/d/1kDqRg8EaI4WQXMaUUbbCGPlsUqEql8kgXCNt6AvMA9I/edit#

docu: sync texts with gdoc

---

src/modes/top10/Top10Sensor.svelte

fix: wrong domain in percentage cases

---

src/modes/timelapse/Player.svelte

closes #513
try to fix the issue using https://refreshless.com/nouislider/number-formatting/#section-aria

fix: set aria option for no-uislider

---

package-lock.json
package.json

release info and zip: https://github.com/cmu-delphi/www-covidcast/releases/tag/v1.9.2

Release 1.9.2

---

src/components/ModeNav.svelte

closes #520 
**Before**:
**After**:

Change max mobile width for mode nav buttons

---

package-lock.json
package.json

release info and zip: https://github.com/cmu-delphi/www-covidcast/releases/tag/v1.9.3

Release 1.9.3

---

src/components/DetailView/DetailView.svelte
src/components/Vega.svelte
src/data/screenshot.js

closes #484
Add button to download image for Details chart.

add download button to detail views

---

src/components/DetailView/VegaTooltip.svelte
src/components/EncodingOptions.svelte
src/components/MapBox/Tooltip.svelte
src/modes/exportdata/ExportData.svelte

style: rename ratios per 100k

---

src/modes/overview/OverviewWrapper.svelte

closes #518, closes #517
re enables the (mobile) panel toggle:

re-enable side panel toggle

---

src/components/MapBox/AMapBoxWrapper.js
src/components/MapBox/MapBox.svelte
src/modes/overview/OverviewWrapper.svelte
src/modes/timelapse/TimeLapse.svelte

closes #528
add an aria description to the map visualization and a proper role. To test just follow the issue but you will hear a different description

fix: add aria label to map

---

src/components/EncodingOptions.svelte
src/components/Search.svelte
src/modes/single/SensorCard.svelte
src/modes/single/SingleLocation.svelte

closes #582 
moreover, improve the search performance
the fix is somehow less Svelte changes which seems to trigger problems

possible fix for single region vega

---

src/components/Options.svelte

closes #611
Tiny edit to change 'defined' to 'available'

Fix tooltip for calendar option

---

src/data/signals.js

hotfix for parsing the new signal descriptions.

bugfix: detecting proper death signal

---

src/modes/single/SensorCard.svelte

closes #656 
Adjust size of Region Details "card" headers, the title line for each sensor, and make it bold. Also adjust spacing of key table.

Shrink card header font size, adjust spacing.

---

.github/stale.yml

There were a couple of commits from v1.10.0 that we need to merge in order to prevent merge conflicts in future merges from dev back to main.

Sync dev to main

---

src/components/MapBox/AMapBoxWrapper.js
src/components/MapBox/InteractiveMap.js
src/maps/index.js

compute rest of ... population on the fly

---

CHANGELOG.md
package-lock.json
package.json
src/stores/constants.js
src/stores/constants.spec.js

release v1.11.1

---

CHANGELOG.md
package-lock.json
package.json
src/stores/constants.js

sync main/v1.11.1 -> dev

---

src/components/Options.svelte
src/customIcons.js

closes #687
- [x[ Unless it is a hotfix it should be merged against the `dev` branch

feat: change date shortcuts

---

src/modes/survey/SurveyQuestion.svelte
src/modes/survey/SurveyTooltip.svelte
src/modes/survey/questions.js

see slack thread
allows to specify the unit in the google doc

feat: specify unit in question doc

---

.github/CONTRIBUTING.md
CHANGELOG.md
src/modes/survey/SurveyQuestion.svelte
src/modes/survey/SurveyTrend.svelte
webpack.config.js

docs: rename COVIDCast to COVIDcast

---

src/modes/survey/SurveyTrend.svelte

fixes the color to be green for good decreasing numbers

fix: trend color for decreasing trends

---

src/components/Calendar/Datepicker.svelte
src/components/Calendar/lib/helpers.js
src/modes/exportdata/ExportData.svelte

closes #718 
fixes the export bug which was due the date picker which is unable to handle corner cases such as when the given date range is invalid. In addition, fix some bugs regarding date selection in the export range and fixes the initial signal selection

fix: export data bug

---

src/components/Disclaimer.svelte
src/components/Search.svelte
src/components/SensorDatePicker2.svelte
src/components/ToggleEncoding.svelte
src/components/UIKitHint.svelte
src/data/fetchData.js
src/formats.js
src/global.css
src/modes/survey/MobileSurveyToc.svelte
src/modes/survey/Overview.svelte
src/modes/survey/Survey.svelte
src/modes/survey/SurveyParameters.svelte
src/modes/survey/SurveyQuestion.svelte
src/modes/survey/SurveyTrend.svelte
src/modes/survey/SurveyValue.svelte
src/modes/survey/format.js
src/modes/survey/questions.js
src/modes/survey/trend.js
src/styles/uikit.css

survey dashboards improvements

---

src/components/Search.svelte
src/modes/survey/MobileSurveyToc.svelte

feat: mobile survey toc on medium devices

---

src/components/MapOverlays.svelte

style: no extra white area

---

src/stores/descriptions.raw.txt

closes #739
Needed to update descriptions.raw.txt.  Not sure if I was supposed to do that as part of #738.

Updates of descriptions.raw.txt

---

src/modes/survey/descriptions.raw.txt
src/stores/descriptions.raw.txt

closes #746 
switches to the new signal and updates the docs

chore(docs): sync meta data docs

---

src/stores/descriptions.raw.txt

feat: sync docs

---

src/modes/mobile/HistoryLineChart.svelte

closes #766 
green is over orange, orange is over violet, violet is over magenta.

feat: order history line by type

---

src/formats.js
src/modes/mobile/IndicatorOverview.svelte
src/stores/trend.js

feat: detect worst date

---

src/components/UIKitHint.svelte
src/formats.js
src/modes/mobile/CasesOverview.svelte
src/modes/mobile/GeoTable.svelte
src/modes/mobile/HistoryLineChart.svelte
src/modes/mobile/HistoryLineTooltip.svelte
src/modes/mobile/IndicatorOverview.svelte
src/modes/mobile/IndicatorTableRow.svelte
src/modes/mobile/RegionMap.svelte
src/modes/mobile/RegionMapTooltip.svelte
src/modes/mobile/SensorUnit.svelte
src/modes/mobile/SensorValue.svelte
src/modes/mobile/SparkLineTooltip.svelte
src/modes/mobile/TrendIndicator.svelte
src/modes/mobile/TrendText.svelte
src/stores/params.js
src/stores/trend.js

based on our discussion from yesterday, I created a similar per 100 unit sign and applied it:

add per 100k unit

---

src/modes/mobile/AllIndicatorOverview.svelte

closes #775
current text: 
incorporates the better text variant and also add a sentence for missing indicators.

fix: improve all indicator summary text.

---

src/modes/exportdata/ExportData.svelte
src/modes/mobile/IndicatorAbout.svelte
src/modes/mobile/IndicatorTable.svelte
src/modes/mobile/IndicatorTableRow.svelte
src/stores/dataSourceLookup.js
src/stores/params.js

based on the export data mode in which we have a similar list:

add nice data sources

---

src/global.css
src/index.html
src/modes/landing/Landing.svelte
src/modes/mobile/AllIndicatorOverview.svelte
src/modes/mobile/CasesOverview.svelte
src/modes/mobile/FancyHeader.svelte
src/modes/mobile/IndicatorOverview.svelte
src/modes/mobile/MobileIndicatorOverview.svelte
src/modes/mobile/RegionMap.svelte
src/modes/mobile/common.css
src/modes/survey/SurveyStats.svelte
src/modes/survey/SurveyValue.svelte

improve landing page for tablet

---

src/modes/mobile/HistoryLineChart.svelte

auto select region in history line chart

feat: auto select region in history line chart

---

src/stores/descriptions.raw.txt

back to doctor visits signal, see https://github.com/cmu-delphi/www-covidcast/pull/762#issuecomment-790818421

feat: back to doctor-visits signal

---

src/modes/landing/Landing.svelte

fix for the landing page link to the survey results

fix: switching to survey mode

---

src/stores/constants.js

to avoid vaccine which is not updated anymore
closes #788
right now it then jumps to:

refactor: change survey default signal to cli

---

src/modes/survey/descriptions.raw.txt

feat: update to latest meta doc

---

src/data/utils.js

fixes to show the raw values in the survey where applicable

fix: raw values not showing in survey

---

src/index.html
src/modes/index.js
src/modes/mobile/FancyHeader.svelte
src/modes/mobile/IndicatorAbout.svelte
src/modes/mobile/MobileIndicatorOverview.svelte
src/modes/mobile/MobileOverview.svelte
src/modes/mobile/MobileParameters.svelte
src/modes/survey/SurveyQuestion.svelte
src/stores/params.js

closes #804, closes #807, closes #806 
see issues for details
in addition: 
> steps to reproduce:
> Load dashboard in national view
> Enter Texas into the location dropdown
> Texas only appears in some of the graphs, and is listed as N/A in the others.
> Devtools indicates we made an API call to ...
should be fixed

various fixes

---

src/data/index.js

shifts the initial latest date by -2 days

feat: shift latest auto date by two days

---

src/components/Calendar/Datepicker.svelte
src/components/Calendar/Popover.svelte
src/components/SensorDatePicker2.svelte
src/components/UIKitHint.svelte
src/modes/mobile/AllIndicatorOverview.svelte
src/modes/mobile/AllIndicatorsText.svelte
src/modes/mobile/IndicatorAbout.svelte
src/modes/mobile/IndicatorDropdown.svelte
src/modes/mobile/MobileIndicatorOverview.svelte
src/modes/mobile/MobileOverview.svelte
src/modes/mobile/RegionMap.svelte
src/modes/mobile/RegionMapWrapper.svelte
src/modes/mobile/common.css
src/modes/survey/Survey.svelte
src/modes/survey/SurveyQuestion.svelte
src/specs/mapSpec.js

closes #819,  closes #818, closes #817, closes #814, closes #815
re 819:
re 818:
re 814:
re 815:
re 816:
notes:
* I moved the calendar below the dropdown and removed the animation. Adding a backdrop over the whole screen would need more time.

another set of small fixes

---

package.json
scripts/generateDescriptions.js
src/modes/mobile/HistoryLineChart.svelte
src/modes/mobile/IndicatorOverview.svelte
src/modes/mobile/TrendTextSummary.svelte
src/modes/survey/IndicatorRevision.svelte
src/modes/survey/IndicatorRevisions.svelte
src/modes/survey/SurveyQuestion.svelte
src/modes/survey/descriptions.raw.txt
src/modes/survey/questions.js
src/specs/lineSpec.js
src/stores/descriptions.raw.txt

closes #756 
add the notion of previous revisions to the survey question page:

survey questions revisions

---

src/modes/survey/descriptions.raw.txt
src/stores/descriptions.raw.txt

fix: small doc changes

---

src/modes/mobile/components/DownloadMenu.svelte
src/stores/params.js

adds an "advanced export button" to the download menu pointing to the export mode:

feat: add advanced export download hint

---

src/modes/mobile/HighlightIndicators.svelte
src/modes/mobile/IndicatorStatsLine.svelte
src/modes/mobile/MobileIndicatorOverview.svelte
src/modes/survey/descriptions.raw.txt
src/stores/params.js

fix: fix unit for non-7day average

---

src/index.html
src/modes/mobile/MobileIndicatorOverview.svelte
src/modes/mobile/MobileOverview.svelte
src/stores/descriptions.raw.txt

changes the title of the pages according to the new "explore" scheme, see also counterpart in www-main soon

feat: rename pages

---

src/modes/mobile/GeoTable.svelte
src/modes/mobile/HistoryLineChart.svelte
src/modes/mobile/HistoryLineTooltip.svelte
src/modes/mobile/IndicatorTable.svelte
src/modes/mobile/RegionMapTooltip.svelte
src/modes/mobile/SensorUnit.svelte
src/modes/mobile/SensorValue.svelte
src/modes/mobile/SparkLineTooltip.svelte
src/modes/mobile/TrendTextSummary.svelte
src/modes/mobile/common.css
src/stores/descriptions.raw.txt
src/stores/params.js

feat: new per 100 short unit

---

src/stores/dataSourceLookup.js
src/stores/descriptions.raw.txt
src/stores/params.js

and fixes the google symptoms signal (datasource typo)

fix: unit for new signal

---

src/modes/mobile/FancyHeader.svelte
src/modes/survey/SurveyQuestion.svelte

style: fix hidden anchor

---

netlify.toml
src/App.svelte
src/components/UIKitHint.svelte
src/data/annotations.js
src/data/api.js
src/data/index.js
src/modes/mobile/CasesOverview.svelte
src/modes/mobile/GeoTable.svelte
src/modes/mobile/HistoryLineChart.svelte
src/modes/mobile/IndicatorAnnotations.svelte
src/modes/mobile/IndicatorTable.svelte
src/modes/mobile/MobileIndicatorOverview.svelte
src/modes/mobile/common.css
src/specs/lineSpec.js
src/stores/index.js
webpack.config.js

closes #601 
current state: 
sub tasks

show data anomaly annotations

---

src/maps/process.js
src/maps/processed/county.csv.js
src/maps/processed/state.csv.js
src/maps/raw/territory/README.md
src/maps/raw/territory/county.csv
src/maps/raw/territory/state.csv

closes #856
so far just added to the "known" data but not part of any shapefiles

feat: add terrorities to name infos

---

src/modes/mobile/HistoryLineChart.svelte

fix: annotations in history line chart

---

src/modes/mobile/components/DownloadMenu.svelte

closes #860
see issue for details

fix: export mode button not working

---

src/modes/mobile/HistoryLineChart.svelte

feat: add warning inline icon in case of multiple regions

---

src/data/annotations.js
src/modes/mobile/IndicatorAnnotation.svelte

see "Source" link at the bottom

feat: add source reference to annotation

---

netlify.toml
scripts/generateDescriptions.js

updating google docs links since I had to copy them to move to a CMU owned gdoc

chore: update gdoc links

---

src/modes/indicator-status/IndicatorStatus.svelte
src/modes/indicator-status/IndicatorStatusTable.svelte

clarifies that it is the "county coverage" in the indicator status page

style: clarify indicator status coverage

---

.github/CONTRIBUTING.md
.gitpod.yml
README.md

closes #882 
update the docu on how to create a release and also add a Gitpod.io configuration
try out Gitpod: https://gitpod.io/#https://github.com/cmu-delphi/www-covidcast/-/tree/sgratzl/contributing

docs: update release process and contributing guide

---

.gitpod.yml

fixes the gitpod config such that it proper installs and starts covidcast automatically

build: fix gitpod config

---

src/data/indicatorInfo.js
src/modes/indicator-status/IndicatorStatusOverview.svelte
src/modes/indicator-status/IndicatorStatusTable.svelte
src/stores/index.js
src/stores/urlHandler.js

closes #892
encodes the visible status indicator in the URL:

Encode visible indicator in hash

---

src/data/annotations.js
src/modes/exportdata/ExportData.svelte

Add annotations to export page

---

src/modes/mobile/HistoryLineChart.svelte
src/modes/mobile/MobileIndicatorOverview.svelte
src/modes/mobile/MobileOverview.svelte
src/modes/mobile/common.css

closes #897 
adds a new "Show All Dates" button

Add simple expandable line chart

---

src/index.html
src/modes/data-anomalies/AnnotationTable.svelte
src/modes/data-anomalies/DataAnomalies.svelte
src/modes/index.js
src/modes/indicator-status/IndicatorStatusTable.svelte
src/modes/mobile/GeoTable.svelte
src/modes/mobile/IndicatorTable.svelte
src/modes/mobile/components/SortColumnIndicator.svelte
src/modes/mobile/components/tableUtils.js
src/stores/dataSourceLookup.js
src/stores/params.js
webpack.config.js

closes #879
adds a new page: `/data-anomalies` which shows the plain list of data anomalies similar to the Excel sheet in a nice way:
Moreover, I refactored the sort table logic for a simpler reuse

Annotation Overview Table

---

src/data/correlation.js
src/data/correlationUtils.js
src/modes/mobile/IndicatorCorrelation.svelte

fix: correlation table lag rendering

---

.github/workflows/release_main.yml
.github/workflows/update_gdocs_data.yml

closes #908 
another attempt to fix the cross repo PR generation. However, we can only proper test it when we do another release

ci(fix): another try of cross repo PRs

---

src/modes/data-anomalies/AnnotationTable.svelte

fix: data anomalies reference link

---

src/blocks/MaxDateHint.svelte
src/components/Calendar/Datepicker.svelte
src/components/RegionDatePicker.svelte
src/components/SensorDatePicker2.svelte
src/components/UIKitHint.svelte
src/data/meta.ts
src/modes/indicator/Indicator.svelte
src/modes/summary/CasesOverview.svelte
src/modes/summary/HighlightIndicators.svelte
src/modes/summary/Summary.svelte
src/modes/survey-results/SurveyQuestion.svelte
src/modes/survey-results/SurveyResults.svelte
src/stores/constants.ts
src/stores/index.ts
src/stores/params.ts
src/stores/stats.ts

add hint about data freshness

---

src/components/RegionDatePicker.svelte
src/components/Search.svelte
src/components/searchHelpers.ts
src/modes/classic/AddAnother.svelte
src/modes/classic/Overview.svelte
src/modes/dashboard/DashboardParameters.svelte
src/modes/dashboard/config/RegionPicker.svelte
src/modes/exportdata/ExportData.svelte
src/modes/indicator-status/IndicatorStatusOverview.svelte
src/modes/lab/PCP.svelte
src/modes/landing/Landing.svelte

improves the search component for cursor navigation beyond the search results. Moreover, refactored the code and cleaned up the Search component.

improve search component

---

src/modes/dashboard/DashboardParameters.svelte
src/modes/dashboard/state.ts

adds a bunch of ga tracking actions across the dashboard application.
Note: we can only test this and see whether we receive things once it s goes live. Google Analytics will just accept input from the primary domain = delphi.cmu.edu

track dashboard interactions

---

src/modes/landing/Landing.svelte

feat: add link to source code

---

src/modes/exportdata/ExportData.svelte

closes #950 
just updates the example, since the CRAN version was already done before

feat: simplify R covidcast library example

---

netlify.toml
src/data/annotations.ts
src/data/api.ts
webpack.config.js

uses the new /covidcast/anomalies endpoint. Note: as an implication, only published entries are shows in all environment (including staging).

feat: switch to /anomalies endpoint

---

src/data/trend.ts

closes #962
division by 0 error:

fix: trend change for 0 base value

---

src/blocks/HistoryLineChart.svelte

closes #968 
hide the show all button on mobile

fix: disable show all on mobile

---

src/blocks/RegionMap.svelte
src/components/vega/Vega.svelte
src/modes/dashboard/Dashboard.svelte
src/modes/dashboard/WidgetFactory.svelte
src/modes/dashboard/state.ts
src/modes/dashboard/widgets/AParallelCoordinatesWidget.svelte
src/modes/dashboard/widgets/ATableWidget.svelte
src/modes/dashboard/widgets/HexMapChartWidget.svelte
src/modes/dashboard/widgets/LineChartWidget.svelte
src/modes/dashboard/widgets/MapChartWidget.svelte
src/modes/dashboard/widgets/WidgetCard.svelte
src/modes/dashboard/widgets/ZoomedMapChartWidget.svelte

minimum height for a grid-cell of 10em -> will overflow + scrollbar when it doesn't fit anymore
new default dashboard:
new empty dashboard text:
fix missing level selector for map:

Dashboard Improvements

---

.github/workflows/create_release.yml
.github/workflows/release_main.yml

since I barely do any release anymore, I don't need to be requested as a reviewer.

ci: remove myself from release review

---

src/modes/exportdata/ExportData.svelte

closes #984 
changes back to a flat list of signals: 
will be useful once each signal has an unique name

export tab flat list of signals

---

src/blocks/HistoryLineChart.svelte

fix: msa mixed signal

---

src/data/api.ts
src/data/meta.ts
src/modes/indicator-status/IndicatorStatusTable.svelte

till they are supported via #995 
fixes the active changes and filters out the weekly signals for now

fix active flag + filter out weekly signals

---

src/blocks/HistoryLineChart.svelte
src/blocks/RegionHexMap.svelte
src/data/fetchData.ts
src/modes/survey-results/SurveyQuestion.svelte
src/modes/survey-results/SurveyResults.svelte

closes #1000 
disables the neighboring counties in the survey view + bugfixing

fix neighbors and disable in survey view

---

src/data/TimeFrame.ts
src/specs/lineSpec.ts

fix raw changes domain

---

src/data/regions.ts

add "Metro Area" suffix

---

src/modes/exportdata/ExportData.svelte

fix export data R code snippet

---

src/stores/index.ts

closes #1024 closes #1033
based on #1032

fix loading of query string date on CTIS page

---

src/components/Search.svelte

improve search style

---

src/blocks/HistoryLineChart.svelte
src/blocks/IndicatorStatsLine.svelte
src/components/DownloadMenu.svelte
src/components/Toggle.svelte
src/modes/survey-results/SurveyQuestion.svelte
src/specs/lineSpec.ts

show stderr and auto scale in CTIS dashboard

---

src/blocks/HistoryLineChart.svelte
src/components/DownloadMenu.svelte
src/data/fetchData.ts
src/data/meta.ts
src/data/sensor.ts
src/modes/dashboard/widgets/LineChartWidget.svelte
src/modes/indicator-status/IndicatorData.svelte
src/modes/indicator/Indicator.svelte
src/modes/summary/Summary.svelte
src/modes/survey-results/SurveyQuestion.svelte
src/specs/lineSpec.ts
src/stores/params.ts

Improve Line Charts

---

src/data/api.ts
src/data/sensor.ts
src/modes/summary/IndicatorTable.svelte
src/styles/mobile.css

Improve Indicator Table

---

src/components/TrendIndicator.svelte
src/data/trend.ts
src/modes/summary/CasesOverview.svelte
src/specs/mapSpec.ts
src/stores/descriptions.raw.txt
src/stores/index.ts

Reverts cmu-delphi/www-covidcast#1069

Revert "fix showing rest of state tooltip"

---

src/modes/indicator/GeoTable.svelte
src/modes/summary/IndicatorTable.svelte
src/styles/mobile.css

Improve tables

---

src/stores/constants.ts
src/stores/index.ts

closes #1088
see description and issue

Set default date to -2

---

src/components/RegionSearch.svelte
src/components/Search.svelte
src/components/SensorSearch.svelte
src/components/SensorSourceSearch.svelte
src/modes/dashboard/config/WidgetPicker.svelte

Fix search style bug in dashboard

---

src/blocks/HistoryLineChart.svelte
src/blocks/RegionMapWrapper.svelte

small style tunings

---

src/modes/indicator/Indicator.svelte
src/stores/constants.ts
src/stores/descriptions.raw.txt

disable maps for google signal

---

src/blocks/RegionHexMap.svelte
src/blocks/RegionMapTooltip.svelte
src/components/HexGrid/HexGridCell.svelte

improve tooltips

---

src/blocks/RegionMapWrapper.svelte
src/modes/indicator-status/IndicatorSignal.svelte
src/modes/indicator/GeoTable.svelte
src/modes/indicator/Indicator.svelte
src/modes/summary/IndicatorTable.svelte
src/modes/summary/Summary.svelte
src/styles/mobile.css

closes #1091 
what about this for better highlighting navigation options? @ryantibs

Tune navigation hints

---

src/blocks/RegionHexMap.svelte
src/blocks/RegionMap.svelte
src/blocks/RegionMapWrapper.svelte
src/components/KPIChange.svelte
src/modes/indicator/Indicator.svelte
src/modes/summary/CasesOverview.svelte
src/stores/constants.ts

closes #1083 
show the state map when there are no counties data

fix State Map for Hospital Admissions

---

src/components/SensorDatePicker2.svelte

show full date in desktop date picker

---

scripts/generateDescriptions.js
src/data/meta.ts
src/data/sensor.ts
src/stores/constants.ts
src/stores/descriptions.raw.txt
src/stores/params.ts
tsconfig.eslint.json

remove short unit from google signal

---

src/components/SensorBadges.svelte
src/modes/summary/IndicatorTable.svelte
src/modes/summary/RowHelper.svelte
src/styles/mobile.css

Mobile Indicator Table

---

src/blocks/HistoryLineChart.svelte

feat: remove include zero toggle

---

src/data/annotations.ts

fixes parsing the data anomalies data sheet such that they weren't rendered.

fix parsing anomalies

---

src/modes/indicator-status/IndicatorStatusTable.svelte
src/modes/indicator-status/data.ts

fix lag sorting

---

src/stores/descriptions.raw.txt

see https://github.com/cmu-delphi/www-covidcast/issues/1049#issuecomment-1008949749

Change Indicator order

---

src/components/SortColumnIndicator.svelte
src/modes/dashboard/widgets/ATableWidget.svelte
src/modes/indicator/GeoTable.svelte

Sorting by relative change

---

src/blocks/RegionMapWrapper.svelte
src/components/Toggle.svelte
src/modes/indicator-status/IndicatorSignal.svelte
src/modes/indicator/Indicator.svelte
src/modes/summary/Summary.svelte

closes #1129 closes #1128 
+ fixes the link switching to keep the parameters

center beehive toggle + fix links

---

src/blocks/RegionCountyMap.svelte
src/blocks/RegionMap.svelte
src/components/HexGrid/ColorLegend.svelte
src/components/vega/vegaFactory.ts
src/data/meta.ts
src/data/sensor.ts
src/data/sensorConstants.ts
src/modes/dashboard/widgets/MapChartWidget.svelte
src/modes/dashboard/widgets/ZoomedMapChartWidget.svelte
src/specs/mapSpec.ts
src/stores/params.ts

closes #1131 
see issue
please try it out, Currently it will only be done for covid-cases signal not for others.

extended scale for covid cases plots

---

src/data/meta.ts
src/data/sensor.ts
src/stores/constants.ts
src/stores/descriptions.raw.txt
src/stores/params.ts
src/stores/questions.raw.txt

feat: extended color scale generalization

---

src/blocks/MaxDateHint.svelte
src/components/RegionDatePicker.svelte
src/components/SensorDatePicker2.svelte
src/modes/dashboard/Dashboard.svelte
src/modes/dashboard/DashboardParameters.svelte
src/modes/indicator/Indicator.svelte
src/modes/summary/CasesOverview.svelte
src/modes/summary/Summary.svelte
src/modes/survey-results/SurveyQuestion.svelte
src/modes/survey-results/SurveyResults.svelte
src/stores/DataFetcher.ts

closes #1143 
another workaround for determining the real max date and max issue

Derive max date/issue for picker and hint

---

src/blocks/HistoryLineChart.svelte
src/specs/lineSpec.ts

fix uncertainty hint for multiple regions

---

src/stores/DataFetcher.ts

closes #1147
workaround by fetching neighboring counties individually instead of at once

Fetch individual regions separately

---

src/stores/descriptions.raw.txt
src/stores/questions.raw.txt
src/stores/questions.ts

closes #1160 
update google docs and add the wave information for the latest wave. 
In addition, added some code to avoid that we running in missing waves again without a fallback. 
Note: I updated all the google doc. There are also some other changes I'm not sure where they are from

hotfix: add missing wave details + workaround to prevent in future

---

scripts/generateDescriptions.js
src/blocks/HistoryLineChart.svelte
src/components/Toggle.svelte
src/data/sensor.ts
src/modes/dashboard/widgets/LineChartWidget.svelte
src/modes/indicator-status/IndicatorData.svelte
src/specs/lineSpec.ts
src/stores/constants.ts
src/stores/descriptions.raw.txt

closes #1138 
similar to the representation of how other regions (neighboring, state, ...) are shown.

Age Groups

---

scripts/generateDescriptions.js
src/modes/survey-results/Overview.svelte
src/stores/index.ts
src/stores/questions.raw.txt
src/stores/questions.ts

closes #1172
the text id here: https://docs.google.com/document/d/1J36nedP6eufeRE3TbyT_BK-ofE5d18kLif2UmORkYDU/edit#
please edit as needed, then I can update the document. It looks like this:
after June 25 the notice text will be shown.

tender ctis warning and ensure not after 2022-06-25

---

scripts/generateDescriptions.js
src/data/fetchTriple.ts
src/data/sensor.ts
src/data/trend.ts
src/stores/DataFetcher.ts
src/stores/constants.ts
src/stores/descriptions.raw.txt
src/stores/params.ts

closes #1139
option to override a signal with another one in the config for a specific geo level. The override is then patched in in both fetching the data and fetching the trend. 
what is missing is adapting the text to notify the user about it at https://docs.google.com/document/d/1llv6xh8jMlmVv7WpyDSv4VgUpFAZQ6QjFUeRxxOinmk/edit#

hospital admission county override

---

src/blocks/HistoryLineChart.svelte
src/blocks/IndicatorFallbackWarning.svelte
src/blocks/IndicatorWarning.svelte
src/blocks/RegionCountyMap.svelte
src/blocks/RegionMap.svelte
src/blocks/RegionMapWrapper.svelte
src/components/KPI.svelte
src/components/KPIChange.svelte
src/components/KPIValue.svelte
src/modes/summary/CasesOverview.svelte
src/stores/DataFetcher.ts
src/stores/params.ts
src/util.ts

addresses #1183 
fallback for the overview + map to the latest available for the levels. Only relevant for the hospital admissions signal, since it has mixed signals on different levels.

Fallback to latest in maps

---

package-lock.json
package.json
src/components/Search.svelte
src/stores/constants.ts

Prep for https://github.com/cmu-delphi/www-main/issues/781
UIKit 3.16.13 breaks layout for the location dropdowns. This PR is a fix.
Status:

Upgrade uikit to 3.16.13

---

.github/workflows/create_release.yml
.github/workflows/release_main.yml
.github/workflows/update_gdocs_data.yml

Convert review assignments to assignees and switch from Katie to george. Review assignments are handled through the release-runner rotation.

Update workflows for Katie's departure

---

src/blocks/NoRecentDataWarning.svelte
src/modes/summary/Overview.svelte

Simplified 'No Recent Data' warning logic.
Removed warning type guessing.

Simplified 'No Recent Data' warning logic.

---

.github/workflows/ci.yml
.github/workflows/create_release.yml
.github/workflows/release_main.yml
.github/workflows/update_gdocs_data.yml

inspired by https://github.com/cmu-delphi/www-main/pull/959

Update GH Actions versions to match those in www-main
