cmu-delphi/www-covidcast

src/stores/constants.js

The original `hospital-admissions:smoothed_adj_covid19` signal becomes defunct 1 October. The replacement signal is `hospital-admissions:smoothed_adj_covid19_from_claims. The new signal was approved late afternoon 1 October and will become available in metadata early morning on 2 October.

Switch to claims-only version of the hospital-admissions signal

---

src/components/MapBox/encodings/bubble.js
src/theme.js

closes #493 
removes the notion of a minimum bubble size:

feat: enforce 0 is no bubble

---

src/stores/constants.js

closes #554
open questions:
* atm. the lowest color is 66% and not 0. The reason is as noted in another issue that it is not enforced in the choropleth map that 0 = first value
notes:
* since it wasn't specified I added it into the 'Public's Behavior' category

feat: add mask signal

---

src/components/DetailView/vegaSpec.js
src/components/Vega.svelte
src/components/customVegaFunctions.js
src/modes/overview/SmallMultiplesPanel.svelte
src/modes/overview/vegaSpec.js
src/modes/single/SingleLocation.svelte

improves the Vega highlighted performance. The main bottleneck was that Vega computes the Voronoi map for (https://vega.github.io/vega-lite/docs/nearest.html) on each highlight update. I deactivated nearest and tried to simulate it by adding hidden vertical lines that are used now for selection. Moreover, I implemented some simple date formatting caching.

improve vega highlight performance

---

src/components/Options.svelte

closes #478
adds three buttons to the date select on a desktop:
* previous day
* latest date in which there is data for this signal
* next day

feat: add date shortcuts

---

src/components/MapOverlays.svelte
src/components/MapSummary.svelte
src/modes/overview/OverviewWrapper.svelte

based on #540 for simpler development
closes #538 
adds a small field to the bottom right of the map showing the "coverage":
a tooltip explains it:
coverage is the percentage of valid level (e.g., county) data for the current signal and date. For example in the given screenshot it shows that the map has only 'Doctor Visits' data for 61% of all counties. Mega Counties are explicitly excluded. 
In the issue I suggested more value but I think the coverage is the most important one

coverage info

---

src/components/MapOverlays.svelte
src/modes/overview/OverviewWrapper.svelte

closes #512 
I created this pull request mainly to remind myself of how the git process works and get familiar with the codebase. If this is not the way you would like to fix this issue totally fine to just reject this.
Adding background class to map title.
Tweaking desktop @media rule so that the map title has a background, rounded on mobile, flat no edges on desktop. 
DESKTOP
Before
After
MOBILE
Before
After

feat: add background to map title for visibility

---

src/components/DetailView/vegaSpec.js

closes #563
Adds day ticks to main chart, and adds week gridlines to both main chart and date range selector.

Add day ticks and week gridlines for Detail view.

---

.github/stale.yml

closes #577 
has to go to main, since most bot just check the primary branch.
see bot: https://github.com/probot/stale

build: add stale-bot configuration

---

src/styles/pg-button.css

closes #477 
Makes the background darker on the toggle buttons "Incidence" vs "Cumulative" and "Counts" vs "Ratios" when selected
Before:
After:

making toggle selection darker

---

package-lock.json
package.json
scripts/changelog.js

adds a script `npm run changelog` that will update a `CHANGELOG.md` file based on the PRs merged between the current checkout out version and the latest main state.
when running right now it will look like:
```md
- [#543](https://github.com/cmu-delphi/www-covidcast/pull/543) Enforce county geo type
- [#558](https://github.com/cmu-delphi/www-covidcast/pull/558) Update population data based on indicator data
- [#530](https://github.com/cmu-delphi/www-covidcast/pull/530) Generate signal constants
- [#526](https://github.com/cmu-delphi/www-covidcast/pull/526) Add background to map title for visibility
- [#545](https://github.com/cmu-delphi/www-covidcast/pull/545) Add date shortcuts
- [#551](https://github.com/cmu-delphi/www-covidcast/pull/551) Enforce 0 is no bubble
- …
```

feat: generate changelog from PRs

---

src/styles/tooltip.css

closes 
- [ x] Unless it is a hotfix it should be merged against the `dev` branch
- [ x] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [x ] Build is successful
- [ x] Code is cleaned up and formatted
Simply darkened the border to 'gray'.  Appears to match the map tooltip style.  Border radius of 4px appears unchanged from the default.   
I also added a small amount of transparency so you can vaguely see what is covered up by the tooltip.

improve vega tooltip styling

---

jest.config.js
src/components/Vega.svelte
src/modes/top10/Top10.svelte
src/util.js

partly fixes #615
Instead of always using 'value', use the primaryField (with 'pValue' replaced with 'value').
Do this for the main sensor and 'others'.
Also globalizes debouncedResize, to reduce refreshes a bit.

Use correct field when computing max of values.

---

src/components/DetailView/DetailView.svelte
src/components/InfoDialog.svelte

closes #598
restores the old focus upon closing a dialog which forces the focus on the close button.

feat: restore focus upon dialog close

---

src/components/DetailView/vegaSpec.js

fix that the initial date range is selected again at the beginning.
the solution was somehow to define a "dummy" data such that the scale has always some date range to convert dates to pixels. As an alternative if you change `autoSize.type` back to `pad` you also don't have the problem (don't know why tho)

fix: date range initial selection was lost

---

src/components/Search.svelte
src/modes/overview/AddAnother.svelte
src/modes/single/SingleLocation.svelte

closes #624
limits the possible items in the add another search box to more of the same level, e.g. here states:

feat: limit add another to same geo level

---

src/components/MapBox/colors.js
src/modes/exportdata/ExportData.svelte

improves the handling when no signal meta data is found in the API (e.g, with the current bar visits and other signals), at least it won't break the app anymore. 
fixes some race condition in loading the export tab directly

more robust missing meta data handling

---

src/stores/constants.js
src/stores/constants.spec.js

closes #680
uses the `default` flag from the google doc to define the default signal

feat: define default signal in google doc

---

src/components/EncodingOptions.svelte
src/components/MapBox/Tooltip.svelte
src/data/fetchData.js
src/data/index.js
src/data/utils.js
src/modes/overview/SmallMultiplesPanel.svelte
src/modes/single/SensorCard.svelte
src/modes/top10/Top10.svelte
src/stores/constants.js
src/stores/ga.js
src/stores/index.js

closes #536 
REQUIRES: the suggested changes in https://docs.google.com/document/d/1RLy4O-gtACVjLEVD_vxyPqvp9nWVhqEjoWAKi68RKpg/edit#
changes the default cases/deaths signal to be the ratio one: 
including side plots

feat: default ratio cases/deaths

---

src/stores/index.js

closes #686
checks before using a `new` JS function which caused the error mentioned in the issue
note: cannot test it cause I don't have this safari version.

feat: add special case for old safari

---

package.json
src/modes/survey/questions.js
webpack.config.js

creates unique bundle names by using webpacks `contenthash` within the file name. However, this requires https://github.com/cmu-delphi/www-main/pull/204 such that www-main also respects the new names.
This will avoid that the website and covidcast are out of sync on a client. A new version of the website will request a different filename from the server, thus a old browser cache hit won't be possible. An old version of the website will also request an old version of covidcast so also from this direction no problem anymore

unique bundle names

---

src/components/Vega.svelte
src/modes/survey/SurveyQuestion.svelte

uses https://getuikit.com/docs/scrollspy to only render vega plots that are visible, improving the initial loading time on the cost of the scrolling time.

feat: use UIKit scrollspy for lazy vega plots

---

src/components/MapBox/AMapBoxWrapper.js
src/components/MapBox/USMapBoxWrapper.js
src/components/MapBox/encodings/choropleth.js
src/components/MapBox/layers.js

change map style: no county border

---

src/components/Search.svelte
src/components/SensorDatePicker2.svelte
src/formats.js
src/global.css
src/maps/infos.js
src/modes/survey/Survey.svelte
src/modes/survey/SurveyParameters.svelte

closes #716 
current state:
@Letsgohyde take a look, please

style: change survey parameter style

---

src/data/fetchData.js

fixes a corner cases when the user is loading state/hrr for the cases/death signal when no data is returned.
e.g., `?date=20210121&region=42003&sensor=indicator-combination-confirmed_7dav_incidence_prop&level=state`

fix: empty tree loading

---

src/components/tooltipUtils.js

closes #739
This change reduces tooltip flickering and improves placement to offset either right or left based on what placement is used (either top-start or top-end, due to the 'flip' option).    
This change also, perhaps coincidentally, substantially reduces the flickering and cut-off issues.  There is still one redraw that is cut-off before it decides to redraw again in flipped mode.

Compute offset for tooltip from placement

---

src/stores/index.js

fixes an issue with browser history navigation
to reproduce:
1. go to https://dev--cmu-delphi-covidcast.netlify.app/overview/?date=20210305
2. click on a cell, e.g. Montana
3. click the browser back button
before: the region wasn't cleared
now it is

fix: separate between empty region and irrelevant parameter

---

src/modes/exportdata/ExportData.svelte

closes #721
select a state when you wanna download counties will results that the state will be expanded to all its counties.

feat: resolve states to their counties

---

src/modes/mobile/HistoryLineChart.svelte
src/specs/lineSpec.js

to increase consistency this change will jump the highlighted date back to its original position when the user leaves the chart:
cons:
* you cannot download a picture with a different date

feat: jump back to selected date upon mouseout

---

src/components/tooltipUtils.js
src/modes/mobile/HistoryLineChart.svelte
src/specs/mapSpec.js

fixes #845, closes #846 , closes #847 
re #845:
re #847
since it is a about a race condition it is difficult to fix. I adapted the code such that only one tooltip content should be visible but I cannot guarantee it.
re #847

fix: reset highlight region in line chart

---

.github/workflows/release_main.yml

try to fix the issue that the release job cannot create a PR in www-main

ci: fix update website job by using common ssh key

---

src/modes/exportdata/ExportData.svelte

closes #874
needs to be firefox!:

fix: export tab layout in firefox

---

.github/workflows/release_main.yml

use a personal access token to create the pr in www-main upon release

ci: use secret token for cross repo access

---

src/data/indicatorInfo.js

fix parsing of the indicator status dates to be more like the other dates of the API
before:
after:

fix: parsing on indicator status dates

---

src/maps/infos.js

fix an issue with the latest version where mega counties are not shown in the map:
before:
after:

fix: mega-counties are not shown

---

src/maps/infos.js
src/modes/mobile/AllIndicatorOverview.svelte
src/modes/mobile/GeoTable.svelte
src/modes/mobile/RegionCountyMap.svelte
src/modes/mobile/RegionHexMap.svelte
src/modes/mobile/RegionMap.svelte
src/modes/mobile/TrendIndicator.svelte
src/modes/mobile/TrendText.svelte
src/modes/mobile/TrendTextSummary.svelte
src/stores/constants.js
src/stores/params.js
src/stores/questions.js
src/stores/trend.js
src/util.js

closes #902
Note: There are a bunch of changes in https://docs.google.com/document/d/1llv6xh8jMlmVv7WpyDSv4VgUpFAZQ6QjFUeRxxOinmk/edit# and https://docs.google.com/document/d/1J36nedP6eufeRE3TbyT_BK-ofE5d18kLif2UmORkYDU/edit# to better reflect this change. 
However, it should be backwards compatible. 
I locally changed one indicator to be neutral and it would look like:

support for neutral indicators

---

src/modes/exportdata/ExportData.svelte

changes the export page to point to the CRAN covidcast package:

feat: link to published r package version

---

src/data/regions.ts
src/stores/descriptions.raw.txt
src/stores/questions.raw.txt

fixes a bug where the state of a region couldn't be resolved
original: 
> On the [dev site](https://dev--cmu-delphi-covidcast.netlify.app/indicator/?date=20210513&sensor=indicator-combination-confirmed_7dav_incidence_prop&region=54007) (but not in the production site), going to "Explore an Indicator", selecting "Cases", then double-clicking on WV, then clicking on one of the counties, creates confusion:  COVIDcast claims that the 1,792,000 population of WV is actually the population of that county, and also that every county hovered over is called "Calhoun County".

fix: county regions are not found

---

src/blocks/HistoryLineChart.svelte
src/components/DownloadMenu.svelte
src/data/signals.ts
src/modes/dashboard/widgets/LineChartWidget.svelte
src/specs/lineSpec.ts
src/stores/constants.ts
src/stores/params.ts

add support to show the raw cumulative signal version for cases/deaths. part of #928 
note: the dark green portion is the amount that has been added for this day

cumulative support for history line charts

---

src/components/vega/Vega.svelte

fixes some corner case notable in the indicator dashboard where all line charts look the same
before this fix:

fix: reused vega spec is not in sync

---

src/components/SensorBadges.svelte
src/data/api.ts
src/data/meta.ts
src/data/sensor.ts
src/formats.ts
src/specs/mapSpec.ts

closes #973 
fixes the dashboard choropleth color pointer. since 0.0 grey is difficult to add since it would be very small. I just removed the arrow for now. Moreover, I fixed the offset issue for pointing to the wrong value

fix dashboard meta update + fix choropleth color pointer

---

src/data/meta.ts

closes #982
fix parsing custom licenses

fix: custom license not parsed

---

src/modes/dashboard/DashboardParameters.svelte
src/modes/dashboard/config/RegionPicker.svelte
src/modes/dashboard/utils.ts
src/modes/index.ts
src/modes/modes.js
src/stores/index.ts

fixes when the dashboard is opened with a non-standard signal (e.g., `/dashboard/?date=20210814&sensor=fb-survey-raw_ili`) that it would resolve to a default signal. 
Also improves the order of the dashboard builder region search by ordering results by type instead purely by name

feat: allow lazy evaluation of sensor param for generic pages

---

src/blocks/IndicatorOverview.svelte

closes #1022 
add small indicators to sparklines to better indicate what the start and end date are:

style: add hint to sparklines about start ends

---

src/components/KPIChange.svelte
src/components/SensorDatePicker2.svelte
src/data/trend.ts
src/modes/summary/IndicatorTable.svelte

closes #1057, closes #1075
show the latest available data within the sparkline time frame:

show latest available data in indicator table

---

src/blocks/HistoryLineChart.svelte
src/components/IndicatorAnnotation.svelte
src/data/annotations.ts
src/data/api.ts
src/specs/lineSpec.ts

closes #1050 
first version of showing an uncertainty annotation in the line chart:
Note
for now implemented as an annotation that can be later one moved to data anomalies sheet used by the delphi-epidata server. However, it will use a new syntax which is not compatible to the current versions deployed. Thus, we test this version here, remove the temporary annotation, and then once deployed readd the annotation to the sheet

add temporary custom annotation for uncertainty

---

src/modes/exportdata/ExportData.svelte

closes #1118 
hide data sources with no "active" signals by default:

Add inactive source toggle

---

src/blocks/HistoryLineChart.svelte
src/blocks/MaxDateHint.svelte
src/modes/indicator/Indicator.svelte
src/modes/summary/CasesOverview.svelte
src/modes/survey-results/SurveyQuestion.svelte

possible workaround/fix for #1123 and #1026
workaround for not having the real latest data date in the meta data
for the latest "show all data" + most recent tooltip

load "latest" of full time frame

---

.github/workflows/release_main.yml
.github/workflows/update_gdocs_data.yml
README.md

closes #1144 
merges the dev branch directly without creating a PR

Auto merge dev upon release

---

src/blocks/HistoryLineChart.svelte
src/components/IndicatorAnnotation.svelte
src/data/annotations.ts

closes #1137 
preparation for a data anomaly over all time that is shown for the raw quidel signal. 
e.g. an entry like:
```
{
problem: 'Test Test',
explanation:
'The way we do smoothing via geo-aggregation can result in a gross mismatch between raw signal availability and smooth signal availability.',
source: 'quidel-covid-ag',
signals: 'covid_ag_raw_pct_positive',
dates: '',
regions: 'state(*);county(*)',
}
```
Note: the format should be compatible with existing format but better be save and add it once it is deployed.
will result in

Quidel Raw Hint

---

src/blocks/HistoryLineChart.svelte
src/blocks/IndicatorOverview.svelte

closes #1159
currently supported in two locations: 
sparline on this page:
and the line chart:
note: as commented in the original issue, changing the date will most likely change the chart itself, too. e.g. it will show a different date window.

dblclick to select date in sparkline and line chart

---

src/components/KPIValue.svelte

fix Cornercase in rounding

---

.github/workflows/create_release.yml

As part of the "Create Release" action in the `www-covidcast` repo, creates a PR in the `delphi-epidata` repo that updates (copies) two text files from `www-covidcast`.
Tested out in [my fork of this repo](https://github.com/rzats/www-covidcast). A link to a successful run can be found [here](https://github.com/rzats/www-covidcast/actions/runs/4821894836), and the PR it created it is https://github.com/cmu-delphi/delphi-epidata/pull/1154.
**PREREQUISITE: Add a secret to this repo called `EPIDATA_PAT`, which is a personal access token with access to both this repo and `delphi-epidata`.**

Sync descriptions and questions to delphi-epidata

---

src/data/meta.ts
src/modes/summary/Overview.svelte
src/modes/summary/Summary.svelte
src/stores/descriptions.raw.txt
src/stores/index.ts

Removing now-defunct JHU signals from the dashboard: replacing the deaths signal with one from `nchs-mortality` (which hasnt been used in the dashboard before), and replacing the cases signal with `doctor-visits`.

Dashboard signal swaps

---

src/blocks/IndicatorWarning.svelte
src/blocks/NoRecentDataWarning.svelte
src/modes/summary/Overview.svelte
src/modes/summary/Summary.svelte

"latest known data" link now preserves context.
Set default date to the date when we have data for all 3 sensors in 'Overview'. When date is present in URL, the date doesn't change to "default date". Added "NoRecentDataWarning" in order to nofity user about "old" data

OKRS-24-55

---

src/modes/exportdata/ExportData.svelte

Fills in the form values on the COVIDcast Export Data page based on URL parameters. This will be used to integrate the export UI with e.g. the EpiVis dashboard or signal documentation, with certain values being pre-filled based on parameters selected on another section of the website.
To test this out, visit the export dashboard on the preview website, then append this set of parameters to the URL:
```
/?data_source=covid-act-now&signal=covid-act-now-pcr_specimen_total_tests&start_day=2024-01-01&end_day=2024-02-02&geo_type=state
```

Set COVIDcast export values based on URL parameters

---

src/stores/descriptions.raw.txt
src/stores/index.ts

This brings the COVIDcast dashboard signals up to date by removing inactive signals and adding newer ones...
* CHANGED:
* `hhs : confirmed_admissions_covid_1d_prop_7dav` --> `hospital-admissions : smoothed_adj_covid19_from_claims`
* REMOVED:
* `hhs : confirmed_admissions_influenza_1d_prop_7dav`
* `chng : smoothed_adj_outpatient_flu`
* ADDED:
* `google-symptoms : s01_smoothed_search`
* `google-symptoms : s03_smoothed_search`
* `google-symptoms : s04_smoothed_search`
* `nssp : pct_ed_visits_covid`
* `nssp : pct_ed_visits_influenza`

Dashboard signals update

---

.github/workflows/ci.yml
.github/workflows/release_main.yml
.github/workflows/update_gdocs_data.yml

The version currently referenced causes actions to fail:
https://github.com/cmu-delphi/www-covidcast/actions/runs/13954044807/job/39081797085#step:1:37
This PR is very similar/analogous to https://github.com/cmu-delphi/delphi-epidata/pull/1603 .

update gh 'actions/cache' away from deprecated version
